apiVersion: database.platform.ohanyere.io/v1alpha1
kind: PostgreSQLClaim
metadata:
  name: ledger-api-postgres
  labels:
    app.kubernetes.io/name: ledger-api
    finops.ohanyere.io/cost-center: commerce
spec:
  environment: dev
  databaseName: ledger-api
  size: small
  version: "16"
  backup:
    enabled: true
    retentionDays: 14
