apiVersion: cache.platform.ohanyere.io/v1alpha1
kind: RedisClaim
metadata:
  name: ledger-api-redis
  labels:
    app.kubernetes.io/name: ledger-api
    finops.ohanyere.io/cost-center: commerce
spec:
  environment: dev
  size: small
  evictionPolicy: allkeys-lru
